language: python
notifications:
    email: false
branches:
    only:
        - master
	- 2023-01-26-no-more-py2
after_success:
    - coveralls
matrix:
  include:
    - python: "2.7"
      env: CI=ci2
    - python: "3.4"
      env: CI=ci3
    - python: "3.5"
      env: CI=ci3
    - python: "3.6"
      env: CI=ci3
    - python: "3.7-dev"
      env: CI=ci3
script: make $CI
install: ""
